name: vcpkg-install

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  vcpkg:
    runs-on: windows-2022

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Check for existing cache
      id: cache_status
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}\vcpkg_installed
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}

    - name: Install vcpkg
      if: steps.cache_status.outputs.cache-hit != 'true'
      shell: cmd
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        cd vcpkg
        git checkout 2024.07.12
        .\bootstrap-vcpkg.bat  && cd ../

    - name: Install dependencies
      if: steps.cache_status.outputs.cache-hit != 'true'
      shell: cmd
      run: |
        ${{ github.workspace }}\vcpkg\vcpkg.exe install --x-install-root ${{ github.workspace }}\vcpkg_installed

    - name: Cache dependencies
      if: steps.cache_status.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}\vcpkg_installed
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}

    - name: Create zip archive for gstreamer
      run: |
        Copy-Item -Recurse ${{ github.workspace }}\vcpkg_installed\x64-windows\bin ${{ github.workspace }}\sensing-dev-gstreamer\bin
        Copy-Item -Recurse ${{ github.workspace }}\vcpkg_installed\x64-windows\lib ${{ github.workspace }}\sensing-dev-gstreamer\lib
        Copy-Item -Recurse ${{ github.workspace }}\vcpkg_installed\x64-windows\include ${{ github.workspace }}\sensing-dev-gstreamer\include
        Compress-Archive -Path ${{ github.workspace }}\sensing-dev-gstreamer -DestinationPath ${{ github.workspace }}\gstreamer-win64.zip

    - name: Create zip archive for gst-plugins
      run: |
        Copy-Item -Recurse ${{ github.workspace }}\vcpkg_installed\x64-windows\plugins\gstreamer ${{ github.workspace }}\sensing-dev-gst-plugins\lib\gstreamer-1.0
        Compress-Archive -Path ${{ github.workspace }}\sensing-dev-gst-plugins -DestinationPath ${{ github.workspace }}\gst-plugins-win64.zip
 
    - name: Create zip archive for tools
      run: |
        Copy-Item -Recurse ${{ github.workspace }}\vcpkg_installed\x64-windows\tools\gstreamer ${{ github.workspace }}\sensing-dev-gst-tools\bin
        Compress-Archive -Path ${{ github.workspace }}\sensing-dev-gst-tools -DestinationPath ${{ github.workspace }}\gst-tools-win64.zip

    - name: Upload gst-plugins
      uses: actions/upload-artifact@v4
      with:
        name: artifact-vcpkg-installed-items
        path: |
          ${{ github.workspace }}/gst-plugins-win64.zip
          ${{ github.workspace }}/gst-tools-win64.zip
          ${{ github.workspace }}/gstreamer-win64.zip